name: Update Bluesky Follower Count

on:
  schedule:
    - cron: "*/5 * * * *"  # Trigger every 15 minutes
  workflow_dispatch:        # Manual trigger option

jobs:
  update-followers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Bluesky follower count
        run: python fetch_followers.py  # Your script that updates the follower count

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add followers.json
          git commit -m "Update follower count" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
